package com.healthguard.common.theme

import androidx.compose.ui.graphics.Color

// HealthGuard brand palette: a calm sage/teal family. Light values come
// straight from the design mock; dark values are the same hues re-toned for
// dark surfaces.

// --- Light ---
val PrimaryLight = Color(0xFF2F6A5F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFB6ECE0)
val OnPrimaryContainerLight = Color(0xFF14463C)
val SecondaryLight = Color(0xFF4A635C)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFDBE9E3)
val OnSecondaryContainerLight = Color(0xFF20352F)
val TertiaryLight = Color(0xFF6E5D2E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFE7E2D8)
val OnTertiaryContainerLight = Color(0xFF4A3F1F)
val BackgroundLight = Color(0xFFF4FAF7)
val OnBackgroundLight = Color(0xFF171D1B)
val SurfaceVariantLight = Color(0xFFEEF4F1)
val OnSurfaceVariantLight = Color(0xFF3F4946)
val SurfaceContainerHighestLight = Color(0xFFDEE5E1)
val SurfaceContainerHighLight = Color(0xFFE4EBE8)
val SurfaceContainerLight = Color(0xFFE9F0EC)
val SurfaceContainerLowLight = Color(0xFFEFF5F1)
val OutlineLight = Color(0xFF6F7975)
val OutlineVariantLight = Color(0xFFBEC9C4)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val InverseSurfaceLight = Color(0xFF2B3230)
val InverseOnSurfaceLight = Color(0xFFECF2EE)
val InversePrimaryLight = Color(0xFF7FD3C2)

// --- Dark ---
val PrimaryDark = Color(0xFF7FD3C2)
val OnPrimaryDark = Color(0xFF14463C)
val PrimaryContainerDark = Color(0xFF14463C)
val OnPrimaryContainerDark = Color(0xFFB6ECE0)
val SecondaryDark = Color(0xFFB1CCC3)
val OnSecondaryDark = Color(0xFF1D352E)
val SecondaryContainerDark = Color(0xFF334B44)
val OnSecondaryContainerDark = Color(0xFFDBE9E3)
val TertiaryDark = Color(0xFFCDC589)
val OnTertiaryDark = Color(0xFF333014)
val TertiaryContainerDark = Color(0xFF4A452A)
val OnTertiaryContainerDark = Color(0xFFE7E2D8)
val BackgroundDark = Color(0xFF101413)
val OnBackgroundDark = Color(0xFFDEE4E0)
val SurfaceVariantDark = Color(0xFF3F4946)
val OnSurfaceVariantDark = Color(0xFFBEC9C4)
val SurfaceContainerHighestDark = Color(0xFF303634)
val SurfaceContainerHighDark = Color(0xFF252B29)
val SurfaceContainerDark = Color(0xFF1C2220)
val SurfaceContainerLowDark = Color(0xFF171D1B)
val OutlineDark = Color(0xFF89938F)
val OutlineVariantDark = Color(0xFF3F4946)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val InverseSurfaceDark = Color(0xFFDEE4E0)
val InverseOnSurfaceDark = Color(0xFF2B3230)
val InversePrimaryDark = Color(0xFF2F6A5F)
